{{- if .Values.config.mysql.secretRefs }}
apiVersion: v1
kind: List
items:
{{- range .Values.config.mysql.secretRefs }}
- apiVersion: v1
  kind: Secret
  metadata:
    name: {{ .name }}
    labels: {{- include "mysql-perf-digests-exporter.labels" $ | nindent 6 }}
  type: Opaque
  stringData:
    user: "CHANGE_ME"
    pass: "CHANGE_ME"
{{- end }}
{{- end }}
