apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-perf-digests-exporter.fullname" . }}
  labels: {{- include "mysql-perf-digests-exporter.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "mysql-perf-digests-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
