{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mysql-perf-digests-exporter.fullname" . }}
  labels:
    release: prometheus
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.serviceMonitor.namespace }}
  namespaceSelector:
    matchNames: [{{ .Values.serviceMonitor.namespace | quote }}]
  {{- end }}
  selector:
    matchLabels: {{- include "mysql-perf-digests-exporter.selectorLabels" . | nindent 6 }}
    {{- with .Values.serviceMonitor.jobLabel }}
    jobLabel: {{ . | quote }}
    {{- end }}
  endpoints:
    {{- if .Values.serviceMonitor.multiTarget }}
    {{- range  .Values.config.mysql.instances }}
    - path: /probe
      port: http
    {{- if $.Values.serviceMonitor.interval }}
      interval: {{ $.Values.serviceMonitor.interval }}
    {{- end }}
    {{- if $.Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ $.Values.serviceMonitor.scrapeTimeout }}
    {{- end }}
      metricRelabelings:
        - action: replace
          replacement: {{ .name }}
          sourceLabels: [ instance ]
          targetLabel: instance
        - action: replace
          replacement: {{ .host }}
          sourceLabels: [ target ]
          targetLabel: target
        {{- if $.Values.serviceMonitor.metricRelabelings -}}
          {{ toYaml $.Values.serviceMonitor.metricRelabelings | nindent 8 }}
        {{- end }}
    {{- if $.Values.serviceMonitor.relabelings }}
      relabelings: {{ toYaml $.Values.serviceMonitor.relabelings | nindent 8 }}
    {{- end }}
      params:
        instance:
          - {{ .name }}
    {{- end }}
    {{- else }}
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
{{- end }}
